global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter_debian12'
    static_configs:
      - targets: ['debian12:9100']

  - job_name: 'node_exporter_rockylinux'
    static_configs:
      - targets: ['rockylinux:9100']